[package]
name = "rsspls"
version = "0.11.2"
edition = "2024"
authors = [
    "Wesley Moore <wes@wezm.net>"
]

homepage = "https://github.com/wezm/rsspls"
repository = "https://github.com/wezm/rsspls.git"

readme = "README.md"
license = "MIT OR Apache-2.0"

description = "Generate RSS feeds from websites"
keywords = ["rss", "cli", "html", "webpage", "feed"]
categories = ["command-line-utilities", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anydate = "0.5.0"
atomicwrites = "0.4.3"
basic-toml = "0.1.9"
cryptoxide = { version = "0.5.1", features = ["blake2"], default-features = false }
futures = { version = "0.3.30", default-features = false, features = ["std"] }
lol_html = "2"
scraper = "0.26"
log = "0.4.22"
mime_guess = { version = "2.0.5", default-features = false }
pico-args = "0.5.0"
pretty_env_logger = "0.5.0"
reqwest = { version = "0.13.2", default-features = false, features = ["gzip", "socks"] }
rss = { version = "2.0.8", features = ["validation"] }
serde = { version = "1.0.205", features = ["derive"] }
simple-eyre = "0.3.1"
tokio = { version = "1.43.1", features = ["rt-multi-thread", "macros", "process"] }
url = "2.5.2"
dirs = "6"

[dependencies.time]
version = "0.3.47"
features = ["parsing", "formatting", "macros"]

[profile.release]
strip = "debuginfo"

[features]
default = ["rust-tls"]
native-tls = ["reqwest/native-tls"]
rust-tls = ["reqwest/rustls"]

[lints.clippy]
# Groups
all = "deny" # deny on all clippy default lints
pedantic = "deny" # deny on all clippy pedantic lints

# Cargo
wildcard_dependencies = "deny"

# rules from the restrictions category
allow_attributes = "deny"
as_conversions = "deny"
await_holding_lock = "deny"
await_holding_refcell_ref = "deny"
dbg_macro = "deny"
disallowed_script_idents = "deny"
exit = "deny"
expect_used = "deny"
indexing_slicing = "deny"
infinite_loop = "deny"
iter_not_returning_iterator = "deny"
large_futures = "deny"
let_underscore_must_use = "deny"
panic_in_result_fn = "deny"
print_stderr = "deny"
print_stdout = "deny"
rc_buffer = "deny"
rc_mutex = "deny"
return_and_then = "deny"
shadow_same = "deny"
string_lit_chars_any = "deny"
string_slice = "deny"
tests_outside_test_module = "deny"
try_err = "deny"
unchecked_time_subtraction = "deny"
unimplemented = "deny"
unnecessary_self_imports = "deny"
unused_result_ok = "deny"
unwrap_in_result = "deny"
use_debug = "deny"
verbose_file_reads = "deny"
# currently in nightly
# missing_lints_inheritance = "deny"
# inline_modules = "deny"
